// <auto-generated />
namespace Brainstorm.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class P7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(P7));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041943481_P7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
